### ISSUE TITLE
How to run this code ?

### ISSUE THREAD

**Issue by ayush0824** [albertchristianto/defect_detection#1]
How to run this code as it would tremendously help me with my research goals.

**Comment by albertchristianto** [comment]
hi @ayush0824, 

Currently, this repository is mainly for my skill demonstration and I only update it when I have some free time. Unless you are satisfied with using the Image Classification method as your research in Defect detection.
I suggest a better repository [Detectron2](https://github.com/facebookresearch/detectron2/tree/main) to do your defect detection research. The repository contains many computer vision tools and deep learning research methods.

best regards,
Albert Christianto
